name: CI - Build Backend


on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_USER: mangara
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Install Docker
        run: sudo apt-get update && sudo apt-get install -y docker.io

      - name: Run Maven with Debugging
        run: mvn -X clean install

      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify